#ifndef incl_HPHP_EXT_XDIFF_H_
#define incl_HPHP_EXT_XDIFF_H_

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include "hphp/runtime/base/base-includes.h"

namespace HPHP {
///////////////////////////////////////////////////////////////////////////////

String HHVM_FUNCTION(xdiff_native);

///////////////////////////////////////////////////////////////////////////////
}

#endif // incl_HPHP_EXT_XDIFF_H_
